<template>
  <div>
    {{lists}}
    {{loves}}
    <mt-checklist 
          title="技术列表"
          :options="[
            {
              label:'HTML5',
              value:1
            },
            {
              label:'CSS3',
              value:2
            },
            {
              label:'JavaScript',
              value:3
            },
            {
              label:'jQuery',
              value:4
            }
          ]"
          v-model="lists">
      </mt-checklist>
      <mt-checklist 
        title="爱好" 
        :options="['学习','跑步','打球','打游戏','刷抖音']"
        v-model="loves">
      </mt-checklist>
      
  </div>
</template>
<script>
export default {
  data(){
    return {
      loves:['跑步','打球'],
      lists:[2,3]
    }
  }
}
</script>